### ISSUE TITLE
SM64 screen flicker

### ISSUE THREAD

**Issue by CornN64** [gonetz/GLideN64#1297]
I compiled the latest version from source on raspberry pi3 (retropie) and the screen start to flicker once the super mario head comes up. I tested a few other games like perfect dark and wave racer which had no problems and was rendering fine...
Looks like some screen buffer issue is causing it.

**Comment by gonetz** [comment]
Could you find the regression commit?

**Comment by loganmc10** [comment]
This started happening at this commit:

313741d8276f0e018ba0c137892d67794468cc28

Turning off Async color buffer copys (or disabling framebuffer emulation) fixes the problem

**Comment by fzurita** [comment]
Interesting. I didn't think the raspberry pi 3 supported any form of Async color buffer read, so it must be falling back to the stub version which shouldn't be doing anything.

**Comment by loganmc10** [comment]
Ya it would be using the stub version, I'm not really sure what caused it, it happens on Linux too if you compile the GLES2 version of GLideN64, which also uses the stub version

**Comment by fzurita** [comment]
If there is no support for sync buffer copies, they should be getting turned off all together in the configuration in my opinion.

**Comment by loganmc10** [comment]
Probably true, I read that Android 7 breaks the GraphicBuffer thing as well (no more access to those "internal" libraries), but I'm not 100% sure about that

**Comment by fzurita** [comment]
It's indeed true, it doesn't work any more, I can tell you from personal experience.

**Comment by HpNoTiQ56** [comment]
Hi,
I've compiled from source today the new NGLIDE64(Raspberry Pi3) and I'm experiencing the flickering issue in SM64!
I've tried mariokart which works fine but can't find a way to make the flickering out of SM64.
I've tried to :
EnableCopyColorToRDRAM : 0 or 1
EnableN64DepthCompare : False/True
EnableFBEmulation : False/True
Here is my config in retropie (Glide section) :
[Video-GLideN64]

# Settings version. Don't touch it.
configVersion = 16
# Crop resulted image (0=disable, 1=auto crop, 2=user defined crop)
CropMode = 0
# Crop width pixels from left and right of resulted image (in native resolution)
CropWidth = 0
# Crop height pixels from top and bottom of resulted image (in native resolution)
CropHeight = 0
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 0
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 1
# Swap frame buffers (0=On VI update call, 1=On VI origin change, 2=On buffer update)
BufferSwapMode = 0
# Frame buffer size is the factor of N64 native resolution.
UseNativeResolutionFactor = 0
# Bilinear filtering mode (0=N64 3point, 1=standard)
bilinearMode = True
# Max level of Anisotropic Filtering, 0 for off
MaxAnisotropy = False
# Size of texture cache in megabytes. Good value is VRAM*3/4
CacheSize = 900
# Enable color noise emulation.
EnableNoise = True
# Enable LOD emulation.
EnableLOD = True
# Enable hardware per-pixel lighting.
EnableHWLighting = False
# Use persistent storage for compiled shaders.
EnableShadersStorage = True
# Make texrect coordinates continuous to avoid black lines between them. (0=Off, 1=Auto, 2=Force)
CorrectTexrectCoords = 0
# Render 2D texrects in native resolution to fix misalignment between parts of 2D image.
EnableNativeResTexrects = False
# Do not use shaders to emulate N64 blending modes. Works faster on slow GPU. Can cause glitches.
EnableLegacyBlending = False
# Enable frame and|or depth buffer emulation.
EnableFBEmulation = True
# Copy auxiliary buffers to RDRAM
EnableCopyAuxiliaryToRDRAM = False
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = True
# Disable buffers read/write with FBInfo. Use for games, which do not work with FBInfo.
DisableFBInfo = True
# Read color buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadColorChunk = False
# Read depth buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadDepthChunk = True
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=copy in async mode)
EnableCopyColorToRDRAM = 2
# Enable depth buffer copy to RDRAM  (0=do not copy, 1=copy from video memory, 2=use software render)
EnableCopyDepthToRDRAM = 2
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Texture filter (0=none, 1=Smooth filtering 1, 2=Smooth filtering 2, 3=Smooth filtering 3, 4=Smooth filtering 4, 5=Sharp filtering 1, 6=Sharp filtering 2)
txFilterMode = 0
# Texture Enhancement (0=none, 1=store as is, 2=X2, 3=X2SAI, 4=HQ2X, 5=HQ2XS, 6=LQ2X, 7=LQ2XS, 8=HQ4X, 9=2xBRZ, 10=3xBRZ, 11=4xBRZ, 12=5xBRZ), 13=6xBRZ
txEnhancementMode = 0
# Deposterize texture before enhancement.
txDeposterize = False
# Don't filter background textures.
txFilterIgnoreBG = False
# Size of filtered textures cache in megabytes.
txCacheSize = 100
# Use high-resolution texture packs if available.
txHiresEnable = True
# Allow to use alpha channel of high-res texture fully.
txHiresFullAlphaChannel = True
# Use alternative method of paletted textures CRC calculation.
txHresAltCRC = False
# Enable dump of loaded N64 textures.
txDump = False
# Zip textures cache.
txCacheCompression = True
# Force use 16bit texture formats for HD textures.
txForce16bpp = False
# Save texture cache to hard disk.
txSaveCache = True
# Path to folder with hi-res texture packs.
txPath = "/home/pi/.local/share/mupen64plus/hires_texture"
# File name of True Type Font for text messages.
fontName = "FreeSans.ttf"
# Font size.
fontSize = 18
# Font color in RGB format.
fontColor = "B5E61D"
# Enable bloom filter
EnableBloom = False
# Brightness threshold level for bloom. Values [2, 6]
bloomThresholdLevel = 4
# Bloom blend mode (0=Strong, 1=Mild, 2=Light)
bloomBlendMode = 0
# Blur radius. Values [2, 10]
blurAmount = 10
# Blur strength. Values [10, 100]
blurStrength = 20
# Force gamma correction.
ForceGammaCorrection = False
# Gamma correction level.
GammaCorrectionLevel = 2.000000
# Show FPS counter.
ShowFPS = False
# Show VI/S counter.
ShowVIS = False
# Show percent counter.
ShowPercent = False
# Counters position (1=top left, 2=top center, 4=top right, 8=bottom left, 16=bottom center, 32=bottom right)
CountersPos = 8

**Comment by fzurita** [comment]
Try BufferSwapMode = 2

**Comment by fzurita** [comment]
Also EnableN64DepthCompare = False and EnableCopyColorToRDRAM = 0

**Comment by HpNoTiQ56** [comment]
I think I've found why this modification don't work,  every time I start a rom, my config is overwritten.
I've tried to modify both ways (Samba share or Winscp) config \\RETROPIE\configs\n64 and opt/retropie/configs/n64

**Comment by loganmc10** [comment]
Ya that's a retropie thing. They need to update their GlideN64 config to set  EnableCopyColorToRDRAM = 0

**Comment by HpNoTiQ56** [comment]
What is a retropie thing? Overwritten config or GlideN64 config not fully configured?
I've tried to add these settings in GlideN64 Custom with no success :

[SUPER%20MARIO]
Good_Name=Super Mario 64 (E) (M3) [!]
frameBufferEmulation\CopyColorToRDRAM=0

**Comment by loganmc10** [comment]
Sorry I meant that RetroPie overwrites the config

**Comment by HpNoTiQ56** [comment]
Ok, now I've updated retropie from source (update retropie-script from  and update all package) and both issue are gone : I can now modify Config withouth it being overwritten and SM64 is not flickering anymor even with copycolortoRDRAM 0.
Now, I've got some textures which don't load :
![img_20170103_143532 1](https://cloud.githubusercontent.com/assets/17127386/21609347/2b427ea6-d1c2-11e6-91de-884e348304e6.jpg)
I've tried every thing marked in this thread.
Should I open another issue?

**Comment by fzurita** [comment]
Try switching blending method. EnableLegacyBlending = True

**Comment by HpNoTiQ56** [comment]
I've already tried to do that but settings is overwritten at launch...
Need to ask how I can manage that in retropie forum...

**Comment by loganmc10** [comment]
You can try lr-glupen64, it should be installed by default on RetroPie. That is a libretro/RetroArch core that implements mupen64plus + GLideN64. It allows you to change settings inside the RetroArch menu and they shouldn't be overridden by RetroPie.

**Comment by HpNoTiQ56** [comment]
Thanks for noticing it but the problem is that it was not performing smooth like GlideN64. One other problem is that I don't know how to modify my saved file to work with lr-glupen. I'll try it tonight and report back here if it as smooth!

**Comment by HpNoTiQ56** [comment]
Hi,  I've tried to use Lr-glupen but retroarch is too hard to configure for now : I can't figure how to load core,  control are all messed up...  I've found that I needed to disable check compatibility in retroarch in all config. Now I've found that enable legacy blending does nothing and the only parameter modifying output is EnableFBEmulation which cause flickering issue if enabled and white texture if disable. I've tried to EnableN64DepthCompare but texture are buggy!  I've played for 2hours straight with white texture and Its been smooth like hell with no crash! I was getting crash before this release so it is the most stable and smooth emulator for me on n64

**Comment by joolswills** [comment]
@loganmc10 `EnableCopyColorToRDRAM = 0` didn't seem to work here - textures still flicker - any other ideas?

**Comment by loganmc10** [comment]
@joolswills are we talking about a whole screen flicker? Or just some textures look transparent/missing? If it's the latter, the only solution currently is to disable framebuffer emulation, it doesn't work correctly on the Raspberry Pi currently

**Comment by joolswills** [comment]
just some textures are white/blank or flash.

**Comment by joolswills** [comment]
Might be best if I rollback this plugin for retropie for now.

**Comment by loganmc10** [comment]
Ya disabling Framebuffer Emulation should fix that issue, it's on my list of things to look at, but my SD card reader stopped working so my Raspberry Pi is out of commission until I shake off my laziness and get another one.

I'll probably end up looking at this again in a week or two, but it's a very pesky problem that seems to be quite difficult to solve

**Comment by joolswills** [comment]
Thanks for the info. Some games require the framebuffer emulation to be properly playable I guess? The framebuffer emulation used to work on the rpi until the commit referenced earlier in this ticket or ?

**Comment by loganmc10** [comment]
This should be fixed in the latest master if you want to retest @CornN64

**Comment by CornN64** [comment]
Nice work!
I updated to todays version (21/3) and SM64 seems to work fine now in the screen flickering regard. I did run quite a few different games and things seems improved speed wise as well.
Not exactly on topic but noise textures both in SM64 and silicon valley are now borked (seems like a scaling problem with the noise textures) this worked ok in previous versions.

**Comment by gonetz** [comment]
Problems with noise fixed in recent commits.

**Comment by CornN64** [comment]
I pulled the latest source and compiled (on retropie on my Pi3) but the noise textures are still not scaling properly and are applied only on one quarter of the screen. I am running in "high res mode" on the Pi3 which means render to 640x480 but the noise texture seems to be applied to only bottom left 320x240 corner of the screen...
This can be seen both in SM64 (when teleporting when only portion of Mario have noise) but even more clearly on the news reader guy in Silicon Valley intro (when there is noise static interruptions).

Sorry I could not get a screen shot but I hope this explains in some detail what is wrong.
