### ISSUE TITLE
Video Interface emulation refactoring

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1414]
There is one problem, which is almost as old as N64 emulation itself. RDP command SetColorImage set only width of color buffer. Height is not set. It is not important for software render, because it renders right into N64 RDRAM. Hardware render needs to know buffer's height to allocate render buffer. Buffer height can be estimated by using parameters of Video Interface, which defines how color buffer will be mapped to TV screen. All hardware plugins, which I know from inside use this possibility. Thus, frame buffer emulation becomes dependent on VI emulation. This dependency does not exist in N64 itself. The estimation does not guarantee to be always correct, and in fact it is often incorrect. The estimation code is complex and full of heuristics, to reduce numbers of errors. Nevertheless, this tie still induce many issues, in particular with PAL games and with games, which use interlaced TV modes.

Recently I invented a way to break that tie between RDP and VI. I'll describe the solution in details in my blog. Implementation requires another major code refactoring. This task is very hard, probably harder than previous large refactoring: #1335. Frame buffer emulation is twisted tight with VI emulation. I untangled most of knots, but it often leads to unpredictable consequences and thus various regressions. From the other side, the new frame buffer and video interface emulation method actually works and brings new fixes.

The new method should fix all issues with PAL games such as shakes (#1396, #305), or screen cut (#375). It also should fix all screen shaking in interlaced modes.
New code also addresses crashes when copying color buffer to RDRAM, such issues should gone. This problem is actually more complex than  RDP - VI relation, so some such issues may remain.
VI emulation fixes finally allowed to properly emulate screen shrink effect in Mia Hamm Soccer and its clones.

The new code is in feature branch Feature_VI_Refactor. My current goal is to find and fix all regressions caused by it and merge it with master. The current master as also full of regressions after #1335, so I'm pretty much busy. Any help (bugs reports, code improvements) is appreciated.

**Comment by gonetz** [comment]
Windows build
https://drive.google.com/file/d/0B0YqMPjGo3B2TmhhR3FjNzJqZXM/view?usp=sharing

**Comment by olivieryuyu** [comment]
great, will check bugs :)

**Comment by AmbientMalice** [comment]
Wave Race renders upside down. Vigilante 8 seems to render flips a lot better with Aux to RAM enabled.

**Comment by ichee** [comment]
Fixes Ocarina of Time subscreen crash in issue #1400, but causes delay in opening subscreen.

Also fixes Majora's Mask screen shaking in issue #1396, but causes a zoom glitch with "Copy auxiliary color buffers to N64 memory" enabled . See below:
![majora](https://cloud.githubusercontent.com/assets/22252639/23829004/c5ff7c4a-06b1-11e7-9b4c-1460609729a1.PNG)

Also, causes a freeze when opening bomber's notebook with "Render N64 frame buffer to output" enabled,

**Comment by ichee** [comment]
Noticed in Majora's Mask that the target cursor above any target is black instead of colored by target type.

![cursor](https://cloud.githubusercontent.com/assets/22252639/23829154/5d54881a-06b7-11e7-8a1d-6c6a607e4df0.PNG)

**Comment by gonetz** [comment]
> Wave Race renders upside down

I forgot to increment  shader  storage version. You need to disable shader storage in settings.

**Comment by ichee** [comment]
I've attached a log created during the above mentioned issues. I don't know if it will be of any use, but here it is.
[gliden64.zip](https://github.com/gonetz/GLideN64/files/836344/gliden64.zip)

**Comment by olivieryuyu** [comment]
cannot remember such a bug before the refactoring. Fifa64 intro.

![oops](https://cloud.githubusercontent.com/assets/8987490/23829902/c9ad1112-06fd-11e7-9a36-817ed6d50ff9.jpg)

**Comment by gonetz** [comment]
> Noticed in Majora's Mask that the target cursor above any target is black instead of colored by target type.

Bug in master. Fixed.

> cannot remember such a bug before the refactoring. Fifa64 intro.

Probably the same bug. Does not appears now.

**Comment by gonetz** [comment]
Update:
https://drive.google.com/file/d/0B0YqMPjGo3B2YmVialRoa2d5OHM/view?usp=sharing

**Comment by olivieryuyu** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/23832103/b689b384-072e-11e7-9346-a598a30534a1.jpg)

vigilante 8

Missile now shows black boxes. Was not the case before i think.

**Comment by gonetz** [comment]
@olivieryuyu Please restart emulator and try again. I don't see the black boxes.

**Comment by ichee** [comment]
Screen flickering in Majora's Mask. Reproducible  by opening the subscreen, followed by opening the bomber's notebook then exit both notebook and subscreen, then open and close the subscreen again.
May need to repeat a few times.

**Comment by gonetz** [comment]
> Screen flickering in Majora's Mask.

Is it a new bug, which is not present in latest Release and in master?

**Comment by ichee** [comment]
Seems to be in latest master as well. Issue is somewhere between 2.0 and commit 5b3b292.

**Comment by gonetz** [comment]
Ok. I need to find and fix regressions caused by changes in this branch first.

**Comment by purplemarshmallow** [comment]
In NASCAR now the upper splitscreen does not work either. The lower one never worked (#691). There are overlapping framebuffers like in Super Bowling. Maybe that's the problem?
![gliden64_nascar_99_000](https://cloud.githubusercontent.com/assets/7283660/23836707/d10628d4-077c-11e7-8adf-91625db9a404.jpg)

**Comment by gonetz** [comment]
Yes, overlapping framebuffers considered as invalid and thus removed. It is crazy idea to make  framebuffers overlapping, and it needs special treatment.

**Comment by oddMLan** [comment]
Was about to point out the intro sequence with the logos shaked in PJ64 2.3, but it's fixed in this branch 😄

**Comment by oddMLan** [comment]
A Bug's Life has no picture with Framebuffer emulation on.

**Comment by oddMLan** [comment]
40 Winks crashes the emulator after the language selection screen. You can work around it by disabling Framebuffer emulation, then the title screen shows correctly. But if you go past it, it crashes.

**Comment by AmbientMalice** [comment]
World Driver Championship seems to crash now.

**Comment by oddMLan** [comment]
![imagen](https://cloud.githubusercontent.com/assets/7278372/23851059/3ca1e408-079f-11e7-8591-e6fda70c58f4.png)
flickering line in DDKR

**Comment by gonetz** [comment]
> A Bug's Life has no picture with Framebuffer emulation on.

It works in LLE, but HLE really does not work.

> 40 Winks crashes the emulator after the language selection screen.

I can't reproduce it.

> World Driver Championship seems to crash now.

At which moment? I run it up to race with no problems.

**Comment by gonetz** [comment]
> flickering line in DDKR

I see, thanks.

**Comment by gonetz** [comment]
Fixed flickering line in DKR
https://drive.google.com/file/d/0B0YqMPjGo3B2bGQ1cUpZRDFnR00/view?usp=sharing

**Comment by gonetz** [comment]
Fixed A Bug's Life

https://drive.google.com/file/d/0B0YqMPjGo3B2elFyVUFnYVYxU0E/view?usp=sharing

**Comment by oddMLan** [comment]
Both confirmed fixed 👍

**Comment by olivieryuyu** [comment]
still have the bug of  #1418 but it is getting better.

However Body Harvest is fixed? I can cross the bridge!! Can someone confirm?

![fixed](https://cloud.githubusercontent.com/assets/8987490/23923397/d0edfaee-0906-11e7-912e-0826e37889d8.jpg)

**Comment by Frank-74** [comment]
Confirmed Body Harvest is fixed.  I can cross the bridge too.  Map displays fine for me as well.

**Comment by AmbientMalice** [comment]
Awesome work.

**Comment by gonetz** [comment]
> Though for some reason, the screenshot from PJ64 is upside down?

It can be. I forgot to rotate image back in screen shots routines. 

> And screenshot is smaller with borders, than the display.

It is very possible. Currently screenshots read from RDP buffer. Video Interface emulation code places it on  display buffer. It can resize the image, take only part of it and place it where necessary. Thus, result picture often differs from screen shot one. I guess that need to be changed too.

**Comment by olivieryuyu** [comment]
For body harverst Map displays fine but the transition between ingame and the map is incorrect. The fb is not handled where it was before.

**Comment by AmbientMalice** [comment]
@gonetz Do you have any idea why Body Harvest is working now? That game has been an enigma of N64 emulation for years.

**Comment by gonetz** [comment]
No idea. I don't even know, which kind of problems exist in it. I did not knew about the bridge issue until the report that it is fixed :) If will give a save from this place, I may check what was wrong.

**Comment by AmbientMalice** [comment]
>No idea. I don't even know, which kind of problems exist in it. I did not knew about the bridge issue until the report that it is fixed :) If will give a save from this place, I may check what was wrong.

It's more than the bridge issue. Until now, Body Harvest has had no collision. You could walk through walls. You couldn't walk up stairs because you'd walk through them. Only Angrylion's worked. Now GLideN64 works. You don't need a save state. You just start a new game and walk forward into the nearest wall.

**Comment by gonetz** [comment]
> You couldn't walk up stairs because you'd walk through them

I still can't :(

**Comment by AmbientMalice** [comment]
Ah, I see. Yea, stairs are still buggy. But wall collision works now. Maybe stairs are buggy due to slightly incorrect depth buffer values?

**Comment by gonetz** [comment]
Well, if collision detection depends on depth buffer, it is possible. You may revert commit 7c51f9455edf to test - it is only commit, which changes depth buffer render work.

**Comment by Frank-74** [comment]
Hmmm, stairs work fine on the building next to the bridge here.  Using default settings except N64 3-point.
![bodyharvest](https://cloud.githubusercontent.com/assets/11056843/23990718/d7dc497c-0a2e-11e7-83fe-22723177a2f1.JPG)

**Comment by AmbientMalice** [comment]
@Frank-74 Try the stairs on the other building, across the road.

**Comment by Frank-74** [comment]
@AmbientMalice 
This one is fine too.  Though the building I'm looking at in this pic, across the way, the stairs are different texture (flat, no steps).  And I walk right through those ones.  There's nothing up there anyway.
![bh2](https://cloud.githubusercontent.com/assets/11056843/23992762/14f5ac0c-0a36-11e7-814d-7dfe0dc12540.JPG)

**Comment by olivieryuyu** [comment]
yes one of the stairs seems buggy, the rest being fine.

**Comment by olivieryuyu** [comment]
nushi zuri

fb does not work anymore

![zarf](https://cloud.githubusercontent.com/assets/8987490/24014682/26985bee-0a86-11e7-89a3-d39a7cc79aec.jpg)

**Comment by gonetz** [comment]
> nushi zuri

it was broken before these changes.

**Comment by loganmc10** [comment]
It does appear that the subscreen delay hack for OoT is now broken.

**Comment by gonetz** [comment]
> It does appear that the subscreen delay hack for OoT is now broken.

I'll check it.

**Comment by gonetz** [comment]
The feature pulled to master. Closed.

**Comment by Frank-74** [comment]
Just a quick mention.

I've played through Greece and Java levels on Body Harvest without any clipping problems.  Now on America.  It seems to be fully playable now.  And good performance too.

**Comment by VinnieVincent123** [comment]
Do anyone know how i can bring the Plugin work? I really love Body Harvest and i want it to play. But I can't make any progression because this stupid clipping problem. I already download your plugin and add it to Project 64, but it still doesn't work. I have the same issue with the bridges and the stairs like before. Anyway it's awesome that a fix for the problem already exist. Sorry Guys for my very bad Englisch, I am from Germany y'know, but I really working hard on my Englisch for more Progrssion and I hope you can understand me. Nice work at all @Frank-74

**Comment by Frank-74** [comment]
@VinnieVincent123 
Make sure 'Copy video card depth buffer to N64 memory' is set to 'In Software'.

Use latest WIP build in this thread: https://github.com/gonetz/GLideN64/issues/1364.

**Comment by VinnieVincent123** [comment]
Where is this Option. I don't find anything like that. I checked every option in the Emu, and i already checked the Advanced Options. I dont have any ideas where is it. I dont know where the Video card depth buffer is. @Frank-74 I know, i'm dumb now because i didn't find that option. But, please help me. :3

**Comment by Frank-74** [comment]
@VinnieVincent123 It's in the configure graphics options.  The GLideN64 configuration.
