### ISSUE TITLE
Majora's Mask Flickering

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1434]
Screen flickering in Majora's Mask. Reproducible by opening the subscreen, followed by opening the bomber's notebook then exit both notebook and subscreen, then open and close the subscreen again.
May need to repeat a few times.

Does not occur with Public Release 2.0.

**Comment by SigmaVirus** [comment]
I thought this was solved recently? I can't reproduce this with this build (latest master)
https://drive.google.com/file/d/0B0YqMPjGo3B2dThIZXctNU1fbkE/view?usp=sharing

I did have a minor issue after with the camera and the screen flashed/flickered but I could solve it by disabling the store shader cache option.

**Comment by ichee** [comment]
Issue is still present in latest master. Tested on all default settings, except with shader cache disabled. Just open the subscreen and bomber's notebook, then close both. Then reopen and close subscreen.
Toggling fullscreen fixes flickering when it starts.

![flicker](https://cloud.githubusercontent.com/assets/22252639/24098798/bbd7add6-0d42-11e7-8076-1182658e912b.gif)

**Comment by SigmaVirus** [comment]
I can confirm this but I had to go in and out several times before I could trigger it.
However it only happened with the option "Same as output resolution" as "Original N64 resolution" worked correctly.

**Comment by ichee** [comment]
Occurs with "Original N64 Resolution" too.

**Comment by SigmaVirus** [comment]
That's weird, I tried 15 times with "Original N64 resolution" and it didn't occur for me but with "Same as output resolution" it happened after a few times.

I'm stumped and don't know what else to say.
Of all 11 games I have Majora's Mask is the only one now causing these weird glitches that behave very random.

**Comment by ichee** [comment]
NTSC. Regression happened sometime after 2.0 was released, as it doesn't have the issue.

**Comment by SigmaVirus** [comment]
I have no clue of what it is that can cause this.

PR 2.0 and after was broken with Majora's Mask (Europe) for me as you can see here:
https://github.com/gonetz/GLideN64/issues/1396

**Comment by loganmc10** [comment]
The flickering is some sort of depth issue, looks the same as the issue that the Raspberry Pi has with Framebuffer emulation, except it happens all the time for the Raspberry Pi on almost every game.

**Comment by SigmaVirus** [comment]
Interesting, thanks for clearing that up.

**Comment by ichee** [comment]
For reference, running:

Windows 10 Pro x64
Intel 4790k @ 4.7Ghz
NVidia GTX Titan X (Maxwell)
Samsung 950 Pro NVMe

**Comment by SigmaVirus** [comment]
We're not to far off:
i7 4790K at stock
ASUS Nvidia 1060 6GB
16GB RAM
Windows 10 x64

**Comment by loganmc10** [comment]
Yep I reproduced with with mupen64plus + Windows 7 + Nvidia, I'll try compare the GL logs from Public Release 2.0 and the current master and see what difference I can see, might take me a bit though.

**Comment by loganmc10** [comment]
I'm still doing some testing on this @ichee can you try enabling "Show FPS" or "Show VI/S" and try to reproduce it? I can't reproduce it if those settings are enabled, I just want to confirm though.

**Comment by ichee** [comment]
It still happens.

**Comment by loganmc10** [comment]
Huh, I guess I just lucked out that one time, I just re-tested and it still happens with "Show VI/S", I'll have to try and bisect and see which commit broke it

**Comment by loganmc10** [comment]
@gonetz I have bisected this issue and 210c9ea64af0a2bcdd9a68fb6ee9432b43099594 is the problem commit. The issue does not happen with the commit prior to it (9edd5a5f181891f91a31545031eda01fd78a0a11)

**Comment by fzurita** [comment]
Hmmm, Maybe the depth buffer is being cleared and we are not re-attaching the depth buffer on those cases because of this change.

**Comment by loganmc10** [comment]
Clearing the depth buffer shouldn't result in the need to re-attach it. But ya, it must be related to the depth buffer being destroyed and the program not realizing it needs to reattach a new depth buffer. I'll look at the GL trace in a bit and see what the difference in the GL API calls is.

**Comment by gonetz** [comment]
Depth buffer is probably attached to previously active buffer, so this optimization is wrong and must be reverted.

**Comment by gonetz** [comment]
Reverted  210c9ea.

**Comment by ichee** [comment]
Fixed.
