### ISSUE TITLE
Mario Party: Coin Block Blitz ground flicker / darkening

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#1912]
In the mini-game "Coin Block Blitz", when characters jump and hit the blocks the ground briefly darkens.

![clipboard04](https://user-images.githubusercontent.com/12134368/46252978-a66b3000-c4b4-11e8-88aa-ca9f8b099bdb.png)
![clipboard06](https://user-images.githubusercontent.com/12134368/46252980-a703c680-c4b4-11e8-9809-0fa93aafc23c.png)

Here is a savestate. The AI characters should automatically begin hitting blocks to demonstrate the problem: [Mario Party (U).pj.zip](https://github.com/gonetz/GLideN64/files/2431199/Mario.Party.U.pj.zip)

This issue is only present in HLE and not in LLE.

----

Additionally, when using LLE during the start of the game (when the blocks fall in) there are some other visual problems: ![clipboard02](https://user-images.githubusercontent.com/12134368/46253003-15e11f80-c4b5-11e8-9ea5-2bddc184e1da.png)

This issue is only present in LLE and not HLE.

**Comment by Tenolius** [comment]
I have the same issue using HLE as well in the same minigame.

**Comment by Kidboy17** [comment]
Can confirm, this happens in newest WIP (Master+FB) as well.
![gliden64_marioparty_000](https://user-images.githubusercontent.com/37382324/46515825-f6caf080-c81a-11e8-8c5e-d56ad9a26c57.png)

**Comment by Kidboy17** [comment]
This is still a current issue in the newest WIP released today. This does not happen with AL.

**Comment by gonetz** [comment]
It happens with all HLE plugins I tested.

**Comment by ShareScene** [comment]
this can be closed.

**Comment by vadosnaprimer** [comment]
If there some miniman hardware spec requirement for this fix? I'm not getting it to work on my old [9800gt](https://i.imgur.com/pme3LGf.png) .

**Comment by gonetz** [comment]
> If there some miniman hardware spec requirement for this fix?

No. It is fixed for all devices which can run GLideN64. You just need a fresh build.

**Comment by thecoreyburton** [comment]
@gonetz As far as I know, he was using the same build and settings as I was when he tested it. For me, the problem was resolved but for him it was still present.

**Comment by gonetz** [comment]
May be you use different rom versions. There was a problem in that fix, see #1954
Now it should work steady.

**Comment by vadosnaprimer** [comment]
This update didn't help me, but oh well, I guess it'd be a nightmare to debug.

**Comment by oddMLan** [comment]
Did you wipe your shader cache?

**Comment by vadosnaprimer** [comment]
How do I check that?

**Comment by oddMLan** [comment]
I believe that shouldve been it... Did you try with another emulator?

**Comment by vadosnaprimer** [comment]
Okay I tested the latest build with m64py and pj64, works fine in them, I guess it's some edge case of our fork maybe.
