### ISSUE TITLE
GLES2 segfaults on load

### ISSUE THREAD

**Issue by mrfixit2001** [gonetz/GLideN64#2280]
I've been trying to get the latest commit to compile and work with my Mali 450 using GLES2. It compiles, but segfaults. I've tracked the issue down to the GLInfo::init() function on opengl_GLInfo.cpp. It's faulting trying to run glGetString. If I bypass all of those, then it segfaults trying to check if GL_ARB_fragment_shader_interlock is supported. It would seem there's an issue with the way it's integrated with my GLES driver. Any help or suggestions would be greatly appreciated!

**Comment by mrfixit2001** [comment]
I should add that all other emulators are running fine, so it's specific to something in this code.

**Comment by gonetz** [comment]
Could you test the fix from #2272?

**Comment by mrfixit2001** [comment]
Just compiled and tested 6d1a5458b82132c9e7e5d241b4aaef3a40578709, sadly the same segfault.

**Comment by gonetz** [comment]
It should be fixed now.

**Comment by gonetz** [comment]
@mrfixit2001 could you confirm that GLES2 is fixed?

**Comment by mrfixit2001** [comment]
I will build and test within the next couple days and report back. Thanks!!

**Comment by mrfixit2001** [comment]
Unfortunately the issue is not resolved :(
Here is a full backtrack of the segfault. I have added a patch which outputs the full GL details at runtime to provide full detail into the gpu compatibliity.
https://pastebin.com/XJGMrxzS

**Comment by mrfixit2001** [comment]
I spent some time tinkering on my own. There appears to be something wrong with the way that EGL is being loaded. 

This line: https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/GLFunctions.cpp#L17
is not working properly on my rk3328, but the line for gles2so works as long as I fix your later restrictive conditional on this line:
https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/GLFunctions.cpp#L205

I would suggest that you either add a new build parameter or accept a run-time parameter that points the code to the correct location of the GLES library and replace this conditional with an ifdef so that if the user provides the value, it's used, otherwise it's not. You could then define it manually in your makefile for the existing defined systems (VC, ODROID, VERO4K).

Closing issue, as I have patched it to work.

**Comment by MX10-AC2N** [comment]
@mrfixit2001 I have rk3328 tvbox with mali 450 too..
I can't use GlideN64 without problem.
Can you explain to me how you make it work properly, please.
Thank
