### ISSUE TITLE
Dino Planet looks so nice but buggy

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2461]
![GLideN64_DINO_PLANET_001](https://user-images.githubusercontent.com/8987490/108596050-d4ea4e00-7382-11eb-9558-8474887eb49e.png)

Apparently there would be some gfx bugs.

Have to be investigated

**Comment by olivieryuyu** [comment]
first bug with the shadows

![GLideN64_DINO_PLANET_002](https://user-images.githubusercontent.com/8987490/108596311-745c1080-7384-11eb-89db-02329f23affe.png)

it could be a bug of emulator as angrylion does not make either

**Comment by olivieryuyu** [comment]
missing textures on polygons (works with angrylion)

save

[DINO PLANET.pj.zip](https://github.com/gonetz/GLideN64/files/6015032/DINO.PLANET.pj.zip)

![GLideN64_DINO_PLANET_004](https://user-images.githubusercontent.com/8987490/108596598-57c0d800-7386-11eb-8b4d-7608211e1fe0.png)

**Comment by gonetz** [comment]
Shadow is fixed.

**Comment by slightlyoutofphase** [comment]
The shadows still have the exact same rendering bug as in the second screenshot in both of Project64 and M64P, even after the very latest commit.

**Comment by Jj0YzL5nvJ** [comment]
> The shadows still have the exact same rendering bug (throughout the entire game, with any settings)

https://imgur.com/vw2wiL0

**Comment by oddMLan** [comment]
> The shadows still have the exact same rendering bug (throughout the entire game, with any settings) as in the second screenshot in both of Project64 and M64P, even after the very latest commit.

delete your shader cache

**Comment by Akira13641** [comment]
Here's a screenshot I just took with the ver latest dev build of GLideN64 paired with the very latest dev build of PJ64. Settings are completely stock, and the game was launched with 100% empty texture and shader cache folders: https://imgur.com/PGzZRg4

**Comment by Akira13641** [comment]
Ok, I just re-tested absolutely everything _very_ carefully and my conclusion is at this point the shadow problem **is** fixed in the M64P version of GLideN64, but **not** fixed in the Project64 version of GLideN64. Not sure how that's the case since they're the same thing mostly I thought, but that's where we stand.

**Comment by LegendOfDragoon** [comment]
Project64 needs 32bit engine disabled

**Comment by Akira13641** [comment]
That does it! Nice find. Thanks a lot. Works perfectly even with a bunch of enhancements enabled: https://imgur.com/lmcZGHT
