### ISSUE TITLE
3-Point Bilinear Filter not working on mip-mapped textures

### ISSUE THREAD

**Issue by Mushman** [gonetz/GLideN64#306]
If a texture uses mip-mapping, the 3-point bilinear filter will not work on it. The textures aren't filtered at all (they're calculated by nearest-neighbour). Textures which have no mip-maps are filtered correctly, even if textures with mip-maps are also onscreen. The bug is still present even if ``EnableLOD`` is turned off.

3-Sample Bilinear Filtering in Donkey Kong 64
![Incorrect 3-sample rendering in DK64](http://i.imgur.com/AM67bow.png)

Mip-Maps Disabled
![Disabling mip-maps with 3-sample still on](http://i.imgur.com/EJ8fBJp.png)

Regular Bilinear Filtering
![Standard bilinear filtering control test](http://i.imgur.com/JMoYWmP.png)

Example in Goldeneye
![Demonstrating 3-sample bilinear implementation in Goldeneye 007](http://i.imgur.com/kfdLopq.png)

This is present in all versions on GLideN64 from the feature's introduction on either emulator platform. Most recent version tested was the Week 24 Performance Fix ``10dfc87`` March 21 build. I'm used NVidia hardware, but not AMD or Intel. I have access to Intel, if you want me to test there.

**Comment by gonetz** [comment]
Use custom texture filtering for custom mip-mapping is non-trivial (impossible?) task.
I'll turn on standard bilinear filtering for mip-mapped textures.

**Comment by olivieryuyu** [comment]
yep that is the best approach :)

**Comment by gonetz** [comment]
Fixed

**Comment by Mushman** [comment]
Reopening because some textures are still not filtered when 3-point is enabled after the fix, like the rock faces in Goldeneye's first level.

![The outcrop texture is not filtered even with the new changes](https://cloud.githubusercontent.com/assets/6550546/7087536/c9698f8e-dfcf-11e4-9673-d5819aba00c3.png)

Additionally, disabling mipmaps causes textures that have mipmaps not to be filtered too.

![With mipmaps disabled, far more textures are not filtered](https://cloud.githubusercontent.com/assets/6550546/7087540/d7d870ee-dfcf-11e4-9370-289a05811eaf.png)

![And it happens in other games like Donkey Kong 64 too](https://cloud.githubusercontent.com/assets/6550546/7087553/fb02c786-dfcf-11e4-9145-87ea44ae9e89.png)

Tested with the Week 26 ``6e93b56`` 28 March builds on both specifications which partially fixed this issue, the latest Week 27 Second Fix ``277ff95`` 9 April Zilmar build and the Week 27 Hotfix ``d3578ec`` 8 April Mupen64Plus build.

**Comment by gonetz** [comment]
Fixed

**Comment by Mushman** [comment]
If mipmaps are disabled, the bug is still present when N64 3-point is selected, but that issue is minor, so I will close this unless someone requests it fixed.
