### ISSUE TITLE
quake 2: wrong colors on corpses (???)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#328]
![ohnnnoo](https://cloud.githubusercontent.com/assets/8987490/6842902/89641b0e-d39d-11e4-9aeb-eedd0ebc121b.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed

**Comment by olivieryuyu** [comment]
actually not fixed. 

If i start a new game and get here, I have the same.

With a save no issue however

**Comment by AmbientMalice** [comment]
Issue seems to be fixed in Public Release. (Coincidentally, the underwater rendering is also seemingly fixed.)

**Comment by purplemarshmallow** [comment]
I still have this problem
But underwater rendering works

**Comment by AmbientMalice** [comment]
I may have had mipmaps disabled, which seems to "fix" the corpse texture bug. My mistake.

**Comment by purplemarshmallow** [comment]
still happens with mip-maps disabled
so it's not a mip-mapping issue

**Comment by gonetz** [comment]
No, it seems that palette texture mode is not set and palette texture loaded as plain intensity texture with no color.

**Comment by olivieryuyu** [comment]
for me it is correct with public release. was it fixed?

**Comment by AmbientMalice** [comment]
No. It happens with random enemies throughout the game with public release.
