### ISSUE TITLE
pokemon stadium missing images

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#415]
In the stadium some images are missing
![1](https://cloud.githubusercontent.com/assets/7283660/7172690/6b54228a-e3ec-11e4-9719-dd0fb3c1da56.png)
After a battle the picture of the trainer is missing
![2](https://cloud.githubusercontent.com/assets/7283660/7172730/e8eedbd6-e3ec-11e4-9d75-a8e549b88216.png)

**Comment by gonetz** [comment]
Is it still actual?

**Comment by purplemarshmallow** [comment]
Yes

**Comment by purplemarshmallow** [comment]
fixed

**Comment by purplemarshmallow** [comment]
My fix caused regressions. Maybe some buffers with 0 height must be created and others should not be created?

**Comment by gonetz** [comment]
Fixed.

**Comment by purplemarshmallow** [comment]
It's not fixed. Some portraits can be missing. correct with https://github.com/purplemarshmallow/GLideN64/commit/9c61274cd3ca395267890fa24aac6eb5ebd9d819
I tried to explain it in #703:
>But another problem is this formula: height = min(height, VI.height). First buffers are created correctly but later this formula sets the height to 0 which is incorrect.

Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQRkRvUWk3NkF6aTQ/view?usp=sharing
![gliden64_pokemon_stadium_001](https://cloud.githubusercontent.com/assets/7283660/9981526/60f1669a-5fc0-11e5-9680-b25bbdcbc857.jpg)

**Comment by gonetz** [comment]
Thanks, I'll check it.

**Comment by gonetz** [comment]
Hmm, if I run the game not from the save state and select "Battle Now!" all images are shown.

**Comment by purplemarshmallow** [comment]
That's how I made the savestate:
select "Battle Now!" 
give up
"Battle Now!" again

**Comment by gonetz** [comment]
I have all portraits with this scenario too, if savestate is not used.
The problem exists indeed when game loaded from the savestate. I'll check your fix for the problem.

**Comment by purplemarshmallow** [comment]
For me portraits are missing even without savestates. What about this? It would fix #718 as well
```
void FrameBufferList::saveBuffer(u32 _address, u16 _format, u16 _size, u16 _width, u16 _height, bool _cfb)
{
	if (VI.width == 0 || (_width != VI.width && _height == 0))
		return;

	OGLVideo & ogl = video();
```

**Comment by gonetz** [comment]
>For me portraits are missing even without savestates.

Have you tested it on the current master?

**Comment by purplemarshmallow** [comment]
Yes

**Comment by gonetz** [comment]
> What about this? It would fix #718 as well

Yes, it fixes the problem. But it is wrong solution. When FrameBufferList::saveBuffer just returns, plugin will continue render to the FBO, which belongs to previous buffer. Thus I added 
```
		m_pCurrent = NULL;
		glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
		return;
```
Since it causes #718, there is another bug somewhere.

**Comment by purplemarshmallow** [comment]
FrameBufferList::saveBuffer is called multiple times for the same buffer. But only the first time height is correct. The second time this formula sets height to 0: height = min(height, VI.height). This is incorrect. This line prevents it:
```
if (VI.width == 0 || (_width != VI.width && _height == 0))
```
if FrameBufferList::saveBuffer  just returns the plugin will continue render to the FBO which belongs to previous buffer. The previous buffer is the buffer with the correct height. Everything will show up correctly. But if you add:
```
m_pCurrent = NULL;
glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
return;
```
or if you save the buffer normally although it has 0 height this buffer will be incorrect because height is 0.

**Comment by gonetz** [comment]
Yes, I see, thanks for the explanation. The problem with your solution is that it is a hack for particular situation. I need general solution.

**Comment by gonetz** [comment]
I've made several changes in fb emulation code. 
Since I'm not sure about regressions, I put them into fb_fixes branch. Latest commit:
https://github.com/gonetz/GLideN64/commit/c953bf98fdc6e42afc0b59f9473eeeb9cd57fcbb

Please test it, especially for regressions.
I tested all known Pokemon Stadium issues, including this one and #718. I also tested games, which use fb effects and which I have a save to test. I did not find any issue, but I'm not a good tester.

**Comment by purplemarshmallow** [comment]
regressions: Pokemon Stadium 2: the bottom of the portraits is cut off
Knockout Kings now seems to freeze I can't get ingame
There are some other problems with Pokemon Stadium games but they are not regressions I'll report that as seperate bugs
![gliden64_pokemon_stadium_2_008](https://cloud.githubusercontent.com/assets/7283660/10081491/69889e76-62f5-11e5-9ca8-e5da03947a95.jpg)
![gliden64_pokemon_stadium_2_009](https://cloud.githubusercontent.com/assets/7283660/10081492/6b5d35b8-62f5-11e5-9d2b-d502db3ae333.jpg)

**Comment by gonetz** [comment]
> regressions: Pokemon Stadium 2: the bottom of the portraits is cut off
This regression reproduced with the current master. That is, it in not introduced by my recent fixes.
I'll check, when it was broken.

**Comment by gonetz** [comment]
Found and fixed:
https://github.com/gonetz/GLideN64/commit/1fb78594c84cda3cbb2ea2d15cbe9696defcf57a

fb_fixes branch updated also:
https://github.com/gonetz/GLideN64/commit/a8456fab2ddc3cefc5dceb9b56120f11056362a3

**Comment by gonetz** [comment]
Knockout Kings fix:
https://github.com/gonetz/GLideN64/commit/8e6fff9199c1204b65abbb53ff115dd8287e65ad

Copy to RDRAM options must be off.

**Comment by purplemarshmallow** [comment]
Ok I'll do more tests.
In Knockout King the plugin always gets the height of the previous (or next?, not sure) buffer. This means height of almost all buffers is wrong.

**Comment by purplemarshmallow** [comment]
Yoshi's Story broke at some point I'm trying to find the commit...

**Comment by gonetz** [comment]
> In Knockout King the plugin always gets the height of the previous (or next?, not sure) buffer. 

At which moment of the game?

>Yoshi's Story broke at some point I'm trying to find the commit...

Fixed

>Edit: Pokemon Puzzle League is now black ingame?

Fixed

I removed fb_fixes branch. FB fixes are now in fb_fixes_2 branch.

**Comment by purplemarshmallow** [comment]
>At which moment of the game?

It happens when auxiliary buffers are created when starting a game: #350
Maybe also in other points in the game. Width of the auxiliary buffer is 73 height is 240. No wonder fill RDRAM used to cause a crash in this game. There's also a large buffer with only ~80 height. height is swapped between these 2 buffers

**Comment by purplemarshmallow** [comment]
@gonetz I tested the fb_fixes_2 branch. I can't find any regressions. I think you can merge it. This turned out to be a very hard problem but now it's fixed :)

**Comment by AmbientMalice** [comment]
I just noticed this while testing the fb_fixes_2 branch. Not sure whether it's present in main branch. Will test as soon as I can.

![gliden64_banjo_tooie_000](https://cloud.githubusercontent.com/assets/10704701/10129673/3b416b46-65f3-11e5-80cd-0e7ce9b79237.png)
![gliden64_banjo_tooie_001](https://cloud.githubusercontent.com/assets/10704701/10129674/3b451f84-65f3-11e5-891b-f459cbf1f76f.png)

Basically, using anti-aliasing with LLE breaks graphics.

**Comment by purplemarshmallow** [comment]
@gonetz I noticed a regression 
In Pokemon Stadium (J) the moitors are broken even more. It only affects LLE and it only heppens after a battle. But monitors never worked correctly: #724  
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQSlZ1ajY4dXl0SGM/view?usp=sharing
![gliden64_pokemon_stadium_002](https://cloud.githubusercontent.com/assets/7283660/10143625/9496b25c-6619-11e5-8718-4501e2304280.jpg)

**Comment by purplemarshmallow** [comment]
This breaks the monitor in LLE: https://github.com/gonetz/GLideN64/commit/16136b04e91f5a29eab15d976a50925e2f1d7925
The good news is the sky is fixed

**Comment by gonetz** [comment]
I accidentally put fb_fixes_2 branch to master, along with fix for  anti-aliasing.

I'll not reset it. I'll try to solve Pokemon Stadium (J) moitors problem for the current master.

@purplemarshmallow thank you for all your help with debugging and testing of fb problems!

**Comment by AmbientMalice** [comment]
Bravo, @gonetz, and good job, @purplemarshmallow. The plugin is in a vastly superior state to 1.2 now, and ridiculously superior to 1.0 and 1.1

**Comment by tony971** [comment]
Should this be closed?

**Comment by purplemarshmallow** [comment]
I'll close when monitors are fixed in LLE. But I think because of this regression it's not worth to reset the fb_fixes_2 merge

**Comment by purplemarshmallow** [comment]
now fixed!

**Comment by gonetz** [comment]
Finally!
