### ISSUE TITLE
shader compilation fails on Nexus Player

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#573]
When trying to launch a game in the nexus player, this is the ADB log output. Nexus player has this GPU: Imagination PowerVR Series 6 Graphics. It looks like the driver is not recognizing the GLSL version defined.

06-09 23:54:06.734: D/GLideN64(15317): shader_compile error: Compile failed.
06-09 23:54:06.734: D/GLideN64(15317): ERROR: 0:1: Syntax error, version 330 not supported
06-09 23:54:06.734: D/GLideN64(15317): ERROR: 1 compilation errors. No code generated.
06-09 23:54:06.734: D/GLideN64(15317): Error in fragment shader:
06-09 23:54:06.734: D/GLideN64(15317): #version 330 core 
06-09 23:54:06.734: D/GLideN64(15317): uniform sampler2D uTex0;		
06-09 23:54:06.734: D/GLideN64(15317): uniform sampler2D uTex1;		
06-09 23:54:06.734: D/GLideN64(15317): uniform sampler2DMS uMSTex0;	
06-09 23:54:06.734: D/GLideN64(15317): uniform sampler2DMS uMSTex1;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp ivec2 uMSTexEnabled;	
06-09 23:54:06.734: D/GLideN64(15317): layout (std140) uniform ColorsBlock {
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uFogColor;			
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uCenterColor;		
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uScaleColor;		
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uBlendColor;		
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uEnvColor;			
06-09 23:54:06.734: D/GLideN64(15317):   lowp vec4 uPrimColor;		
06-09 23:54:06.734: D/GLideN64(15317):   lowp float uPrimLod;			
06-09 23:54:06.734: D/GLideN64(15317):   lowp float uK4;				
06-09 23:54:06.734: D/GLideN64(15317):   lowp float uK5;				
06-09 23:54:06.734: D/GLideN64(15317): };								
06-09 23:54:06.734: D/GLideN64(15317): uniform mediump vec2 uScreenScale;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uAlphaCompareMode;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uAlphaDitherMode;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uColorDitherMode;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uGammaCorrectionEnabled;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uFogUsage;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp ivec2 uFb8Bit;		
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp ivec2 uFbFixedAlpha;
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uSpecialBlendMode;
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp int uEnableAlphaTest;	
06-09 23:54:06.734: D/GLideN64(15317): uniform lowp float uAlphaTestValue;
06-09 23:54:06.734: D/GLideN64(15317): uniform mediump vec2 uDepthScale;	
06-09 23:54:06.734: D/GLideN64(15317): in lowp vec4 vShadeColor;	
06-09 23:54:06.734: D/GLideN64(15317): in mediump vec2 vTexCoord0;
06-09 23:54:06.734: D/GLideN64(15317): in mediump vec2 vTexCoord1;
06-09 23:54:06.734: D/GLideN64(15317): in mediump vec2 vLodTexCoord;
06-09 23:54:06.734: D/GLideN64(15317): in lowp float
06-09 23:54:06.736: D/GLideN64(15317): shader_compile error: Compile failed.
06-09 23:54:06.736: D/GLideN64(15317): ERROR: 0:1: Syntax error, version 330 not supported
06-09 23:54:06.736: D/GLideN64(15317): ERROR: 1 compilation errors. No code generated.
06-09 23:54:06.736: D/GLideN64(15317): Error in fragment shader:
06-09 23:54:06.736: D/GLideN64(15317): #version 330 core 
06-09 23:54:06.736: D/GLideN64(15317): uniform sampler2D uTex0;		
06-09 23:54:06.736: D/GLideN64(15317): uniform sampler2D uTex1;		
06-09 23:54:06.736: D/GLideN64(15317): uniform sampler2DMS uMSTex0;	
06-09 23:54:06.736: D/GLideN64(15317): uniform sampler2DMS uMSTex1;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp ivec2 uMSTexEnabled;	
06-09 23:54:06.736: D/GLideN64(15317): layout (std140) uniform ColorsBlock {
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uFogColor;			
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uCenterColor;		
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uScaleColor;		
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uBlendColor;		
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uEnvColor;			
06-09 23:54:06.736: D/GLideN64(15317):   lowp vec4 uPrimColor;		
06-09 23:54:06.736: D/GLideN64(15317):   lowp float uPrimLod;			
06-09 23:54:06.736: D/GLideN64(15317):   lowp float uK4;				
06-09 23:54:06.736: D/GLideN64(15317):   lowp float uK5;				
06-09 23:54:06.736: D/GLideN64(15317): };								
06-09 23:54:06.736: D/GLideN64(15317): uniform mediump vec2 uScreenScale;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uAlphaCompareMode;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uAlphaDitherMode;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uColorDitherMode;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uGammaCorrectionEnabled;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uFogUsage;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp ivec2 uFb8Bit;		
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp ivec2 uFbFixedAlpha;
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uSpecialBlendMode;
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp int uEnableAlphaTest;	
06-09 23:54:06.736: D/GLideN64(15317): uniform lowp float uAlphaTestValue;
06-09 23:54:06.736: D/GLideN64(15317): uniform mediump vec2 uDepthScale;	
06-09 23:54:06.736: D/GLideN64(15317): in lowp vec4 vShadeColor;	
06-09 23:54:06.736: D/GLideN64(15317): in mediump vec2 vTexCoord0;
06-09 23:54:06.736: D/GLideN64(15317): in mediump vec2 vTexCoord1;
06-09 23:54:06.736: D/GLideN64(15317): in mediump vec2 vLodTexCoord;
06-09 23:54:06.736: D/GLideN64(15317): in lowp float

**Comment by gonetz** [comment]
I guess, you use GLES3.1 version of the plugin. Are you sure that your Nexus player has GLES 3.1 support?

**Comment by fzurita** [comment]
I think so, see here:
https://gfxbench.com/device.jsp?benchmark=gfx31&D=Asus+Nexus+Player&testgroup=info

**Comment by gonetz** [comment]
I set wrong #version string for GLES 3.1. I've made a fix, just need to test it on my device.

**Comment by fzurita** [comment]
OK, I'll try it out once the fix makes it to github.

**Comment by gonetz** [comment]
Fixed.
Test apk:
https://drive.google.com/file/d/0B0YqMPjGo3B2aVF4YnJCTnJFX0U/view?usp=sharing

**Comment by fzurita** [comment]
We got further along. New shader compilation error:

06-10 09:27:03.147: D/GLideN64(7741): [gles2GlideN64]: Create setting videomode 1440x1080
06-10 09:27:03.148: D/GLideN64(7741): OpenGL version string: OpenGL ES 3.1 build 1.4@3300288
06-10 09:27:03.148: D/GLideN64(7741): OpenGL vendor: Imagination Technologies
06-10 09:27:03.148: D/GLideN64(7741): OpenGL renderer: PowerVR Rogue G6430
06-10 09:27:03.148: D/GLideN64(7741): OpenGL major version: 3
06-10 09:27:03.148: D/GLideN64(7741): OpenGL minor version: 1
06-10 09:27:03.148: D/GLideN64(7741): ImageTexture support: yes
06-10 09:27:03.148: D/GLideN64(7741): Max Anisotropy: 0.000000
06-10 09:27:03.167: D/GLideN64(7741): shader_compile error: Compile failed.
06-10 09:27:03.167: D/GLideN64(7741): ERROR: 0:1: Syntax error, version 420 not supported
06-10 09:27:03.167: D/GLideN64(7741): ERROR: 1 compilation errors. No code generated.
06-10 09:27:03.168: D/GLideN64(7741): Error in fragment shader:
06-10 09:27:03.168: D/GLideN64(7741): #version 420 core											
06-10 09:27:03.168: D/GLideN64(7741): layout(binding = 0) uniform sampler2D uDepthImage;		
06-10 09:27:03.168: D/GLideN64(7741): layout(binding = 0, r16ui) uniform readonly uimage2D uZlutImage;
06-10 09:27:03.168: D/GLideN64(7741): layout(binding = 1, r16ui) uniform readonly uimage2D uTlutImage;
06-10 09:27:03.168: D/GLideN64(7741): uniform lowp vec4 uFogColor;								
06-10 09:27:03.168: D/GLideN64(7741): out lowp vec4 fragColor;									
06-10 09:27:03.168: D/GLideN64(7741): lowp float get_alpha()										
06-10 09:27:03.168: D/GLideN64(7741): {															
06-10 09:27:03.168: D/GLideN64(7741):   ivec2 coord = ivec2(gl_FragCoord.xy);					
06-10 09:27:03.168: D/GLideN64(7741):   highp float bufZ = texelFetch(uDepthImage,coord, 0).r;	
06-10 09:27:03.168: D/GLideN64(7741):   const highp int iZ = bufZ > 0.999 ? 262143 : int(floor(bufZ * 262143.0));
06-10 09:27:03.168: D/GLideN64(7741):   int y0 = clamp(iZ/512, 0, 511);							
06-10 09:27:03.168: D/GLideN64(7741):   int x0 = iZ - 512*y0;									
06-10 09:27:03.168: D/GLideN64(7741):   uint iN64z = imageLoad(uZlutImage,ivec2(x0,y0)).r;		
06-10 09:27:03.168: D/GLideN64(7741):   highp float n64z = clamp(float(iN64z)/65532.0, 0.0, 1.0);
06-10 09:27:03.168: D/GLideN64(7741):   int index = min(255, int(n64z*255.0));					
06-10 09:27:03.168: D/GLideN64(7741):   uint iAlpha = imageLoad(uTlutImage,ivec2(index,0)).r;			
06-10 09:27:03.168: D/GLideN64(7741):   return float(iAlpha/256)/255.0;						
06-10 09:27:03.168: D/GLideN64(7741): }														
06-10 09:27:03.168: D/GLideN64(7741): void main()											
06-10 09:27:03.168: D/GLideN64(7741): {														
06-10 09:27:03.168: D/GLideN64(7741):   fragColor = vec4(uFogColor.rgb, get_alpha());		
06-10 09:27:03.168: D/GLideN64(7741): }

**Comment by gonetz** [comment]
Hmm. Why you enabled N64 depth compare? :)

**Comment by gonetz** [comment]
Fixed compilation errors in all shaders for GL ES 3.1
Some of them does not work on Android though :(

New apk:
https://drive.google.com/file/d/0B0YqMPjGo3B2aktUWXlSaTNyNGc/view?usp=sharing

**Comment by fzurita** [comment]
I'll try this one once I get home. What kind of features are going to be missing in GL ES 3.1?

**Comment by fzurita** [comment]
All the shader compilation errors are gone. Unfortunately, the plugin still doesn't seem to be working correctly in he Nexus Player. I'm getting a black screen and nothing helpful is appearing in adb. It almost looks like the plugin is crash but there is no backtrace. Here is the adb output:

06-10 21:22:35.327: I/Core(17307): Goodname: Super Mario 64 (U) [!]
06-10 21:22:35.327: I/Core(17307): Name: SUPER MARIO 64      
06-10 21:22:35.327: I/Core(17307): MD5: 20B854B239203BAF6C961B850A4A51A2
06-10 21:22:35.327: I/Core(17307): CRC: 635A2BFF 8B022326
06-10 21:22:35.327: I/Core(17307): Imagetype: .z64 (native)
06-10 21:22:35.327: I/Core(17307): Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
06-10 21:22:35.327: I/Core(17307): Version: 1444
06-10 21:22:35.327: I/Core(17307): Manufacturer: Nintendo
06-10 21:22:35.327: I/Core(17307): Country: USA
06-10 21:22:35.331: D/UI-Console(17307): Cheat codes disabled.
06-10 21:22:35.347: I/UI-Console(17307): using Video plugin: 'GLideN64' v2.0.0
06-10 21:22:35.378: I/UI-Console(17307): using Audio plugin: 'Mupen64Plus OpenSLES Audio Plugin' v2.0.0
06-10 21:22:35.378: I/UI-Console(17307): using Input plugin: 'Mupen64Plus Android Input Plugin' v1.0.0
06-10 21:22:35.380: I/UI-Console(17307): using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
06-10 21:22:35.411: I/Core(17307): Setting video mode: 1440x1080
06-10 21:22:35.411: I/GameSurface(17307): Creating GL context
06-10 21:22:35.420: V/GameSurface(17307): Found EGL display connection
06-10 21:22:35.420: V/GameSurface(17307): Initialized EGL display connection
06-10 21:22:35.424: V/GameSurface(17307): Found compatible EGL frame buffer configuration
06-10 21:22:35.440: V/GameSurface(17307): Created EGL rendering context
06-10 21:22:35.441: V/GameSurface(17307): Created EGL window surface
06-10 21:22:35.451: V/GameSurface(17307): Bound EGL rendering context to EGL window surface
06-10 21:22:35.460: I/GameSurface(17307): Created GL context OpenGL ES 3.1 build 1.4@3300288
06-10 21:22:35.461: D/GLideN64(17307): [gles2GlideN64]: Create setting videomode 1440x1080
06-10 21:22:35.463: D/GLideN64(17307): OpenGL version string: OpenGL ES 3.1 build 1.4@3300288
06-10 21:22:35.463: D/GLideN64(17307): OpenGL vendor: Imagination Technologies
06-10 21:22:35.463: D/GLideN64(17307): OpenGL renderer: PowerVR Rogue G6430
06-10 21:22:35.463: D/GLideN64(17307): OpenGL major version: 3
06-10 21:22:35.463: D/GLideN64(17307): OpenGL minor version: 1
06-10 21:22:35.463: D/GLideN64(17307): ImageTexture support: yes
06-10 21:22:35.463: D/GLideN64(17307): Max Anisotropy: 0.000000
06-10 21:22:35.511: W/adb(32173): type=1400 audit(0.0:22913893): avc: denied { read } for name="usb" dev="tmpfs" ino=12552 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=0
06-10 21:22:35.528: I/ActivityManager(557): Process com.android.keychain (pid 16385) has died
06-10 21:22:35.590: I/ActivityManager(557): Process android.process.media (pid 3979) has died
06-10 21:22:35.595: I/ActivityManager(557): Process com.google.android.atv.widget (pid 32409) has died
06-10 21:22:35.640: I/ActivityManager(557): Process android.process.acore (pid 16354) has died
06-10 21:22:35.643: I/ActivityManager(557): Process eu.chainfire.supersu (pid 16411) has died
06-10 21:22:35.644: I/ActivityManager(557): Process com.google.android.gms.wearable (pid 6592) has died
06-10 21:22:35.644: I/GameSurface(17307): Destroying GL context
06-10 21:22:35.645: V/GameSurface(17307): Unbound EGL rendering context from EGL window surface
06-10 21:22:35.648: V/GameSurface(17307): Destroyed EGL window surface
06-10 21:22:35.652: V/GameSurface(17307): Destroyed EGL rendering context
06-10 21:22:35.652: V/GameSurface(17307): Terminated EGL display connection
06-10 21:22:35.657: D/Core(17307): Rom closed.

**Comment by gonetz** [comment]
Need to insert more log messages to find what's going on.

Do the GLES3.0 and GLES2.0 versions of the plugin work on your device?

**Comment by fzurita** [comment]
I just tried the other 2 versions. I got the same results.

**Comment by fzurita** [comment]
The nexus player does have an x86  CPU. It may have to do with that.

**Comment by gonetz** [comment]
As I know, GLideN64 really does not work on x86 Android devices. No idea why.

**Comment by fzurita** [comment]
I think, it may be crashing, but I'm not sure. I'll try to add some logging to see how far it's getting. Maybe I can help you out.
