### ISSUE TITLE
Rat attack missing geometry

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#600]
If framebuffer emulation is enabled almost all geometry is missing
If framebuffer emulation is disabled the geometry appears
happens with HLE and LLE
![gliden64_rat_attack_000](https://cloud.githubusercontent.com/assets/7283660/8449441/c4309cc8-1fd1-11e5-9ce8-6066c3f9f8fc.jpg)
![gliden64_rat_attack_001](https://cloud.githubusercontent.com/assets/7283660/8449442/c6915552-1fd1-11e5-85fc-e8696acefd39.jpg)

**Comment by LegendOfDragoon** [comment]
Just to be clear, have you tried cpu interpreter? The recompiler is bugged for this game (assuming you're using PJ64).

**Comment by purplemarshmallow** [comment]
CPU interpreter does not help
The problem is GLideN64's framebuffer emulation

**Comment by AmbientMalice** [comment]
Enabling accurate N64 depth seems to make geometry appear. Likely similar issue to Toy Story 2.

**Comment by loganmc10** [comment]
Enabling N64 Depth Compare does indeed make things show up, but it's still not perfect:

![capture](https://user-images.githubusercontent.com/848146/27832754-12c8e8ec-608d-11e7-9b6c-40a0879d39fc.PNG)

![capture2](https://user-images.githubusercontent.com/848146/27832757-156fbbd4-608d-11e7-8798-75874a306948.PNG)

Also the opening "credits" should have a projector light like this (this screenshot is from Glide64), it is missing in GLideN64 even with N64 Depth Compare:
![capture3](https://user-images.githubusercontent.com/848146/27832803-48a6b930-608d-11e7-9ca6-cc28475a30ca.PNG)

**Comment by theboy181** [comment]
opps

**Comment by gonetz** [comment]
Fixed

**Comment by theboy181** [comment]
The light, and the Geometry still broken for me on the latest WIP#3 ? What do I need to do?

**Comment by gonetz** [comment]
Wait for next WIP build or take latest mupen64plus build from AppVeyor

**Comment by loganmc10** [comment]
Rat Attack doesn't work with Mupen64Plus

**Comment by gonetz** [comment]
Ok. You may use test build from #1981 then. It is current master + vi fixes. Rat attack works with it.
