### ISSUE TITLE
Dark rift: missing 2d

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#648]
![sight](https://cloud.githubusercontent.com/assets/8987490/9131412/8e5a83ca-3ceb-11e5-859d-e4ee55fdd2e4.jpg)

for instance pause menu in game

it works ok with Glide64

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
In HLE the text is still missing
In LLE the text appears
![1](https://cloud.githubusercontent.com/assets/7283660/13554392/deaccd08-e3a6-11e5-91e6-7372ef1b2d06.jpg)

![2](https://cloud.githubusercontent.com/assets/7283660/13554393/e26d9e7c-e3a6-11e5-9411-95fcfed61e89.jpg)

**Comment by olivieryuyu** [comment]
#224 is for the bug on the background and is now fixed.

this issue is still ongoing, with the rest of the issues for this game (2 other tickets)

**Comment by gonetz** [comment]
Text is fixed now.
What are the 2 other tickets?

**Comment by AmbientMalice** [comment]
Here:

https://github.com/gonetz/GLideN64/issues/649
https://github.com/gonetz/GLideN64/issues/626

**Comment by gonetz** [comment]
Thanks

**Comment by olivieryuyu** [comment]
fixed
